/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas.akhirku;

/**
 *
 * @author asus
 */
public class pilihpaket extends javax.swing.JFrame {
     int pulsa = 100000;
    /**
     * Creates new form pilihpaket
     */
    public pilihpaket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        info = new javax.swing.JTextArea();
        harian = new javax.swing.JButton();
        malam = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        bulanan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hasilTeks = new javax.swing.JTextArea();
        back = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        harianPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        harian3k = new javax.swing.JButton();
        harian5k = new javax.swing.JButton();
        harian10k = new javax.swing.JButton();
        bulananPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bulanan50k = new javax.swing.JButton();
        bulanan60k = new javax.swing.JButton();
        malamPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        malam5k = new javax.swing.JButton();
        malam10k = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));

        info.setEditable(false);
        info.setBackground(new java.awt.Color(255, 184, 184));
        info.setColumns(20);
        info.setFont(new java.awt.Font("Champagne & Limousines", 1, 16)); // NOI18N
        info.setForeground(new java.awt.Color(255, 255, 255));
        info.setRows(5);
        jScrollPane1.setViewportView(info);

        backgroundPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 360, 90));

        harian.setBackground(new java.awt.Color(255, 255, 255));
        harian.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        harian.setForeground(new java.awt.Color(39, 60, 117));
        harian.setText("HARIAN");
        harian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harianActionPerformed(evt);
            }
        });
        backgroundPanel.add(harian, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 100, 40));

        malam.setBackground(new java.awt.Color(255, 255, 255));
        malam.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        malam.setForeground(new java.awt.Color(39, 60, 117));
        malam.setText("MALAM");
        malam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malamActionPerformed(evt);
            }
        });
        backgroundPanel.add(malam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 100, 40));

        keluar.setBackground(new java.awt.Color(255, 255, 255));
        keluar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        keluar.setForeground(new java.awt.Color(39, 60, 117));
        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        backgroundPanel.add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 100, 40));

        bulanan.setBackground(new java.awt.Color(255, 255, 255));
        bulanan.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        bulanan.setForeground(new java.awt.Color(39, 60, 117));
        bulanan.setText("BULANAN");
        bulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulananActionPerformed(evt);
            }
        });
        backgroundPanel.add(bulanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, 40));

        jLabel2.setFont(new java.awt.Font("YummyCupcakes", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Beli paket data sesukamu");
        backgroundPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 190, 30));

        jLabel9.setFont(new java.awt.Font("Curlz MT", 1, 40)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DATAKU");
        backgroundPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, 50));

        jScrollPane2.setBackground(new java.awt.Color(153, 153, 255));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        hasilTeks.setEditable(false);
        hasilTeks.setBackground(new java.awt.Color(255, 184, 184));
        hasilTeks.setColumns(20);
        hasilTeks.setFont(new java.awt.Font("Champagne & Limousines", 1, 15)); // NOI18N
        hasilTeks.setForeground(new java.awt.Color(255, 255, 255));
        hasilTeks.setRows(5);
        hasilTeks.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, null, null));
        jScrollPane2.setViewportView(hasilTeks);

        backgroundPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 430, 80));

        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Downloads\\back.jpg")); // NOI18N
        back.setText("jLabel2");
        backgroundPanel.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 611, -1));

        mainPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        mainPanel.add(jLayeredPane1, "card6");

        harianPanel.setBackground(new java.awt.Color(255, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\300mb.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\500mb.jpg")); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\1gb.jpg")); // NOI18N
        jLabel4.setText("jLabel4");

        harian3k.setText("3000");
        harian3k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harian3kActionPerformed(evt);
            }
        });

        harian5k.setText("5000");
        harian5k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harian5kActionPerformed(evt);
            }
        });

        harian10k.setText("10000");
        harian10k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harian10kActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout harianPanelLayout = new javax.swing.GroupLayout(harianPanel);
        harianPanel.setLayout(harianPanelLayout);
        harianPanelLayout.setHorizontalGroup(
            harianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(harianPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(harian3k)
                .addGap(101, 101, 101)
                .addComponent(harian5k)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(harian10k)
                .addGap(49, 49, 49))
            .addGroup(harianPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        harianPanelLayout.setVerticalGroup(
            harianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(harianPanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(harianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(harianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(harian3k)
                    .addComponent(harian5k)
                    .addComponent(harian10k))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(harianPanel, "card2");

        bulananPanel.setBackground(new java.awt.Color(255, 204, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\12gb.jpg")); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\15gb.jpg")); // NOI18N
        jLabel6.setText("jLabel6");

        bulanan50k.setText("50000");
        bulanan50k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulanan50kActionPerformed(evt);
            }
        });

        bulanan60k.setText("60000");
        bulanan60k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulanan60kActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bulananPanelLayout = new javax.swing.GroupLayout(bulananPanel);
        bulananPanel.setLayout(bulananPanelLayout);
        bulananPanelLayout.setHorizontalGroup(
            bulananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bulananPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(bulananPanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(bulanan50k)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bulanan60k)
                .addGap(103, 103, 103))
        );
        bulananPanelLayout.setVerticalGroup(
            bulananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bulananPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(bulananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bulananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bulanan50k)
                    .addComponent(bulanan60k))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        mainPanel.add(bulananPanel, "card3");

        malamPanel.setBackground(new java.awt.Color(255, 204, 255));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\3gb.jpg")); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\Documents\\6gb.jpg")); // NOI18N
        jLabel8.setText("jLabel8");

        malam5k.setText("5000");
        malam5k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malam5kActionPerformed(evt);
            }
        });

        malam10k.setText("10000");
        malam10k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malam10kActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout malamPanelLayout = new javax.swing.GroupLayout(malamPanel);
        malamPanel.setLayout(malamPanelLayout);
        malamPanelLayout.setHorizontalGroup(
            malamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(malamPanelLayout.createSequentialGroup()
                .addGroup(malamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(malamPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(malamPanelLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(malam5k)
                        .addGap(110, 110, 110)
                        .addComponent(malam10k)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        malamPanelLayout.setVerticalGroup(
            malamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(malamPanelLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(malamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(malamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(malam5k)
                    .addComponent(malam10k))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        mainPanel.add(malamPanel, "card4");

        backgroundPanel.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 470, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void harianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harianActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(harianPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_harianActionPerformed

    private void bulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulananActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(bulananPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_bulananActionPerformed

    private void malamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malamActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.add(malamPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_malamActionPerformed

    private void malam5kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malam5kActionPerformed
        pulsa -= 5000;
        if (pulsa<0){
            hasilTeks.setText("Transaksi gagal\nPulsa anda tidak mencukupi untuk membeli paket ini\nSilahkan isi ulang");
        }else{
        String no = login.nomorTeks.getText();
        info.setText("Hai "+no+"\nSisa pulsa anda adalah Rp."+pulsa);
        lalalala out = new lalalala();
        out.setharga(5000);
        out.setBerlaku("jam 19.00 sampai 00.00");
        out.setjenis("Malam 3GB");
        hasilTeks.setText("Transaksi telah berhasil pulsa anda berkurang sebanyak Rp."+out.getharga()+"\nPaket "+out.getjenis()+" Sudah dapat digunakan\nMasa berlaku dari "+out.getberlaku());        
    }//GEN-LAST:event_malam5kActionPerformed
}
    private void harian3kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harian3kActionPerformed
        pulsa -= 3000;
        if (pulsa<0){
            hasilTeks.setText("Transaksi gagal\nPulsa anda tidak mencukupi untuk membeli paket ini\nSilahkan isi ulang");
        }else{
        String no = login.nomorTeks.getText();
        info.setText("Hai "+no+"\nSisa pulsa anda adalah Rp."+pulsa);
        lalalala out = new lalalala();
        out.setharga(3000);
        out.setBerlaku("sampai 00.00");
        out.setjenis("Harian 300MB");
        hasilTeks.setText("Transaksi telah berhasil pulsa anda berkurang sebanyak Rp."+out.getharga()+"\nPaket "+out.getjenis()+" Sudah dapat digunakan\nMasa berlaku "+out.getberlaku());
    }//GEN-LAST:event_harian3kActionPerformed
    }
    private void harian5kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harian5kActionPerformed
        pulsa -= 5000;
        if (pulsa<0){
            hasilTeks.setText("Transaksi gagal\nPulsa anda tidak mencukupi untuk membeli paket ini\nSilahkan isi ulang");
        }else{
        String no = login.nomorTeks.getText();
        info.setText("Hai "+no+"\nSisa pulsa anda adalah Rp."+pulsa);
        lalalala out = new lalalala();
        out.setharga(5000);
        out.setBerlaku("sampai 00.00");
        out.setjenis("Harian 500MB");
        hasilTeks.setText("Transaksi telah berhasil pulsa anda berkurang sebanyak Rp."+out.getharga()+"\nPaket "+out.getjenis()+" Sudah dapat digunakan\nMasa berlaku "+out.getberlaku());        
    }//GEN-LAST:event_harian5kActionPerformed
    }
    private void harian10kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harian10kActionPerformed
        pulsa -= 10000;
        if (pulsa<0){
            hasilTeks.setText("Transaksi gagal\nPulsa anda tidak mencukupi untuk membeli paket ini\nSilahkan isi ulang");
        }else{
        String no = login.nomorTeks.getText();
        info.setText("Hai "+no+"\nSisa pulsa anda adalah Rp."+pulsa);
        lalalala out = new lalalala();
        out.setharga(10000);
        out.setBerlaku("3 Hari dari pembelian");
        out.setjenis("Harian 1GB");
        hasilTeks.setText("Transaksi telah berhasil pulsa anda berkurang sebanyak Rp."+out.getharga()+"\nPaket "+out.getjenis()+" Sudah dapat digunakan\nMasa berlaku "+out.getberlaku());
    }//GEN-LAST:event_harian10kActionPerformed
    }
    private void bulanan50kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulanan50kActionPerformed
        pulsa -= 50000;
        if (pulsa<0){
            hasilTeks.setText("Transaksi gagal\nPulsa anda tidak mencukupi untuk membeli paket ini\nSilahkan isi ulang");
        }else{
        String no = login.nomorTeks.getText();
        info.setText("Hai "+no+"\nSisa pulsa anda adalah Rp."+pulsa);
        lalalala out = new lalalala();
        out.setharga(50000);
        out.setBerlaku("sampai 30 hari setelah pembelian");
        out.setjenis("Bulanan 12GB");
        hasilTeks.setText("Transaksi telah berhasil pulsa anda berkurang sebanyak Rp."+out.getharga()+"\nPaket "+out.getjenis()+" Sudah dapat digunakan\nMasa berlaku "+out.getberlaku());        

    }//GEN-LAST:event_bulanan50kActionPerformed
    }
    private void bulanan60kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulanan60kActionPerformed
        pulsa -= 60000;
        if (pulsa<0){
            hasilTeks.setText("Transaksi gagal\nPulsa anda tidak mencukupi untuk membeli paket ini\nSilahkan isi ulang");
        }else{
        String no = login.nomorTeks.getText();
        info.setText("Hai "+no+"\nSisa pulsa anda adalah Rp."+pulsa);
        lalalala out = new lalalala();
        out.setharga(60000);
        out.setBerlaku("sampai 30 hari setelah pembelian");
        out.setjenis("Bulanan 12GB");
        hasilTeks.setText("Transaksi telah berhasil pulsa anda berkurang sebanyak Rp."+out.getharga()+"\nPaket "+out.getjenis()+" Sudah dapat digunakan\nMasa berlaku "+out.getberlaku());        
    }//GEN-LAST:event_bulanan60kActionPerformed
}
    private void malam10kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malam10kActionPerformed
        pulsa -= 10000;
        if (pulsa<0){
            hasilTeks.setText("Transaksi gagal\nPulsa anda tidak mencukupi untuk membeli paket ini\nSilahkan isi ulang");
        }else{
        String no = login.nomorTeks.getText();
        info.setText("Hai "+no+"\nSisa pulsa anda adalah Rp."+pulsa);
        lalalala out = new lalalala();
        out.setharga(10000);
        out.setBerlaku("jam 19.00 sampai 00.00");
        out.setjenis("malam 6GB");
        hasilTeks.setText("Transaksi telah berhasil pulsa anda berkurang sebanyak Rp."+out.getharga()+"\nPaket "+out.getjenis()+" Sudah dapat digunakan\nMasa berlaku dari "+out.getberlaku());        
    
    }//GEN-LAST:event_malam10kActionPerformed
}
    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pilihpaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pilihpaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pilihpaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pilihpaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pilihpaket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton bulanan;
    private javax.swing.JButton bulanan50k;
    private javax.swing.JButton bulanan60k;
    private javax.swing.JPanel bulananPanel;
    private javax.swing.JButton harian;
    private javax.swing.JButton harian10k;
    private javax.swing.JButton harian3k;
    private javax.swing.JButton harian5k;
    private javax.swing.JPanel harianPanel;
    private javax.swing.JTextArea hasilTeks;
    public static javax.swing.JTextArea info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton keluar;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton malam;
    private javax.swing.JButton malam10k;
    private javax.swing.JButton malam5k;
    private javax.swing.JPanel malamPanel;
    // End of variables declaration//GEN-END:variables
}
